title = "DynastyProcess.com"
baseURL = "https://dynastyprocess.com"
tags = ["data analysis", "rstats", "data science", "dynasty fantasy football"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-36766776-4"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "High quality resources for DynastyFF"
  author = "Tan Ho, Joe Sydlowski"
  description = "Delivering high quality open data and resources for dynasty fantasy football."
  logoBig = "/images/_dynastyprocess/dp_hex.svg"
  logoSmall = "/images/_dynastyprocess/dp_wordmark.svg"
  favicon = "/images/_dynastyprocess/dp_hex.svg"
  opengraphImage = "/images/_dynastyprocess/logo-hex-small.png"
  email = "hello@dynastyprocess.com"
  googleTagManager = ""
  customCSS = true

  # Social media links in footer
  github = "dynastyprocess"
  twitter = "dynastyprocess"

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = false

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Posts"
  url  = "/#blog"
  weight = 3

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
